services:
  # Apstra MCP Server - supports both stdio and HTTP transports
  apstra-mcp-server:
    build: .
    container_name: apstra-mcp-server
    ports:
      - "8080:8080"
    volumes:
      # Mount config file
      - ./apstra_config.json:/app/apstra_config.json:ro
    environment:
      - PYTHONUNBUFFERED=1
    command: ["python3", "apstra_mcp.py", "-t", "http", "-H", "0.0.0.0"]
    restart: unless-stopped
    networks:
      - apstra-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Optional: Nginx reverse proxy for SSL termination
  nginx:
    image: nginx:alpine
    container_name: apstra-mcp-nginx
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - apstra-mcp-server
    restart: unless-stopped
    networks:
      - apstra-network
    profiles:
      - with-nginx

networks:
  apstra-network:
    driver: bridge